#
# https://www.serverless.com/framework/docs/providers/aws/guide/events
#
service: zectr-export
frameworkVersion: "3"
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
functions:
  indexAPI:
    handler: ./controllers/index-controller.handler
    events:
      - httpApi: GET /index.html
  slidesAPI:
    handler: ./controllers/slides-controller.handler
    events:
      - httpApi: POST /slides
  bucketsAPI:
    handler: ./controllers/buckets-controller.handler
    events:
      - httpApi: GET /buckets
plugins:
  - serverless-offline
  - serverless-dotenv-plugin
