#
# https://www.serverless.com/framework/docs/providers/aws/guide/events
#
service: zectr-export
frameworkVersion: "3"
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
functions:
  web-resourceAPI:
    handler: ./web-resources.handler
    events:
      - httpApi: GET /index.html
      - httpApi: GET /buckets
      - httpApi: GET /slides
plugins:
  - serverless-offline
  - serverless-dotenv-plugin
